
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;






public class PassengerForm extends javax.swing.JFrame {
   
PreparedStatement pst;

public Connection connect() {
    try {
         Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/airport_db", "root", ""); ;
        Class.forName("com.mysql.cj.jdbc.Driver");
        return DriverManager.getConnection("jdbc:mysql://localhost:3306/airport_db", "root", "");
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Database connection failed: " + e.getMessage());
        return null;
    }
}


    /**
     * Creates new form PassengerForm
     */
    public PassengerForm() {
        initComponents();
        loadPassengerData();
    }
    
    private void loadPassengerData() {
    try {
        Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/airport_db", "root", "");

        String sql = "SELECT * FROM passengers";
        PreparedStatement pstmt;
        pstmt = conn.prepareStatement(sql);
        ResultSet rs = pstmt.executeQuery();

        // Create table model with column names
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("Name");
        model.addColumn("Passport No");
        model.addColumn("Nationality");
        model.addColumn("Gender");
        model.addColumn("DOB");
        model.addColumn("Flight No");
        model.addColumn("Seat No");
        model.addColumn("Check-In");

        // Fill model with data from ResultSet
        while (rs.next()) {
            model.addRow(new Object[]{
                rs.getString("name"),
                rs.getString("passport_number"),
                rs.getString("nationality"),
                rs.getString("gender"),
                rs.getDate("date_of_birth"),
                rs.getString("flight_number"),
                rs.getString("seat_number"),
                rs.getBoolean("check_in_status") ? "Yes" : "No"
            });
        }

        // Set model to JTable
        tablePassengers.setModel(model);

        conn.close();
    } catch (Exception e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "Error loading data: " + e.getMessage());
    }
}

    public Connection getConnection() {
    Connection conn = null;
    try {
        Class.forName("com.mysql.cj.jdbc.Driver");
        conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/airport_db", "root", "");
    } catch (Exception e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(null, "Database Connection Failed!");
    }
    return conn;
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblName = new javax.swing.JLabel();
        lblPassport = new javax.swing.JLabel();
        lblNationality = new javax.swing.JLabel();
        lblGender = new javax.swing.JLabel();
        lblDOB = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblSeat = new javax.swing.JLabel();
        lblCheckIn = new javax.swing.JLabel();
        btnInsert = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        txtName = new javax.swing.JTextField();
        txtPassport = new javax.swing.JTextField();
        txtNationality = new javax.swing.JTextField();
        txtDOB = new javax.swing.JTextField();
        txtFlight = new javax.swing.JTextField();
        txtSeat = new javax.swing.JTextField();
        chkCheckIn = new javax.swing.JCheckBox();
        comboGender = new javax.swing.JComboBox<>();
        scrollPane = new javax.swing.JScrollPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablePassengers = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        Next = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblName.setBackground(new java.awt.Color(102, 204, 255));
        lblName.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblName.setForeground(new java.awt.Color(102, 102, 102));
        lblName.setText("     Name:");

        lblPassport.setBackground(new java.awt.Color(153, 204, 255));
        lblPassport.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblPassport.setForeground(new java.awt.Color(102, 102, 102));
        lblPassport.setText("Passport Number:");

        lblNationality.setBackground(new java.awt.Color(153, 204, 255));
        lblNationality.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblNationality.setForeground(new java.awt.Color(102, 102, 102));
        lblNationality.setText("    Nationality:");

        lblGender.setBackground(new java.awt.Color(153, 204, 255));
        lblGender.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblGender.setForeground(new java.awt.Color(102, 102, 102));
        lblGender.setText("      Gender:");

        lblDOB.setBackground(new java.awt.Color(153, 204, 255));
        lblDOB.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblDOB.setForeground(new java.awt.Color(102, 102, 102));
        lblDOB.setText("  Date of Birth :");

        jLabel2.setBackground(new java.awt.Color(153, 204, 255));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("Flight Number:");

        lblSeat.setBackground(new java.awt.Color(153, 204, 255));
        lblSeat.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblSeat.setForeground(new java.awt.Color(102, 102, 102));
        lblSeat.setText("Seat number :");

        lblCheckIn.setBackground(new java.awt.Color(153, 204, 255));
        lblCheckIn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblCheckIn.setForeground(new java.awt.Color(102, 102, 102));
        lblCheckIn.setText("Check -in-status :");

        btnInsert.setBackground(new java.awt.Color(204, 255, 255));
        btnInsert.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        btnInsert.setForeground(new java.awt.Color(0, 153, 102));
        btnInsert.setText("Insert");
        btnInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertActionPerformed(evt);
                btnInsertActionListener(evt);
            }
        });

        btnDelete.setBackground(new java.awt.Color(255, 204, 204));
        btnDelete.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        btnDelete.setForeground(new java.awt.Color(255, 51, 51));
        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnUpdate.setBackground(new java.awt.Color(0, 204, 255));
        btnUpdate.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        btnUpdate.setForeground(new java.awt.Color(255, 204, 0));
        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        txtNationality.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNationalityActionPerformed(evt);
            }
        });

        comboGender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female", "Others" }));
        comboGender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboGenderActionPerformed(evt);
            }
        });

        tablePassengers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Name", "Passport no.", "Nationality", "Gender", "Date of Birth(yyyy-mm-dd)", "Flight No.", "Seat no.", "Check-in-status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Long.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Boolean.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tablePassengers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablePassengersMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablePassengers);

        scrollPane.setViewportView(jScrollPane1);

        jLabel1.setBackground(new java.awt.Color(204, 204, 204));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 204, 255));
        jLabel1.setText("AIRPORT MANAGEMENT");

        jButton1.setFont(new java.awt.Font("Sitka Text", 1, 18)); // NOI18N
        jButton1.setText("Back");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        Next.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Next.setText("NEXT");
        Next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NextActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lblCheckIn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGap(16, 16, 16)
                                        .addComponent(lblDOB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(lblPassport, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)
                                    .addComponent(lblNationality, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblName, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblGender, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addComponent(lblSeat, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(comboGender, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtName)
                                    .addComponent(txtPassport)
                                    .addComponent(txtNationality)
                                    .addComponent(txtDOB)
                                    .addComponent(txtFlight)
                                    .addComponent(txtSeat, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
                                    .addComponent(chkCheckIn))))
                        .addGap(39, 39, 39)
                        .addComponent(scrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 632, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(200, 200, 200)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 444, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(19, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jButton1)
                .addGap(71, 71, 71)
                .addComponent(btnInsert)
                .addGap(45, 45, 45)
                .addComponent(btnDelete)
                .addGap(42, 42, 42)
                .addComponent(btnUpdate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Next)
                .addGap(67, 67, 67))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtName)
                            .addComponent(lblName, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtPassport)
                            .addComponent(lblPassport, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblNationality, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtNationality)
                                .addGap(2, 2, 2)))
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblGender, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(comboGender))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtDOB)
                            .addComponent(lblDOB, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtFlight, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblSeat, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSeat, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblCheckIn, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                            .addComponent(chkCheckIn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(101, 101, 101))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(scrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 448, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnInsert)
                    .addComponent(btnDelete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)
                    .addComponent(Next))
                .addGap(29, 29, 29))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comboGenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboGenderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboGenderActionPerformed

    private void txtNationalityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNationalityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNationalityActionPerformed

    private void btnInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertActionPerformed
        // TODO add your handling code here:
        // Step 1: Validate input first
    if (
        txtName.getText().trim().isEmpty() ||
        txtPassport.getText().trim().isEmpty() ||
        txtNationality.getText().trim().isEmpty() ||
        txtDOB.getText().trim().isEmpty() ||
        txtFlight.getText().trim().isEmpty() ||
        txtSeat.getText().trim().isEmpty()
    ) {
        JOptionPane.showMessageDialog(this, "Please fill in all the fields.");
        return;
    }

    // Step 2: Get input values
    String name = txtName.getText();
    String passport = txtPassport.getText();
    String nationality = txtNationality.getText();
    String gender = comboGender.getSelectedItem().toString();
    String dob = txtDOB.getText();
    String flightNo = txtFlight.getText();
    String seatNo = txtSeat.getText();
   int checkIn = chkCheckIn.isSelected() ? 1 : 0;

    // Step 3: Prepare SQL query
    String sql = "INSERT INTO passengers (name, passport_number, nationality, gender, date_of_birth, flight_number, seat_number, check_in_status) VALUES (?, ?, ?, ?, ?, ?, ?, ?)";

    // Step 4: Try inserting into DB
    try {
        Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/airport_db", "root", "");

        PreparedStatement pstmt = conn.prepareStatement(sql);
        pstmt.setString(1, name);
        pstmt.setString(2, passport);
        pstmt.setString(3, nationality);
        pstmt.setString(4, gender);
        pstmt.setDate(5, java.sql.Date.valueOf(dob));  // Format: yyyy-MM-dd
        pstmt.setString(6, flightNo);
        pstmt.setString(7, seatNo);
        pstmt.setInt(8, checkIn);

        int rowsInserted = pstmt.executeUpdate();

        if (rowsInserted > 0) {
            JOptionPane.showMessageDialog(this, "Passenger inserted successfully!");
            
            loadPassengerData();  // Refresh the table after insert
            

        }

        pstmt.close();
        conn.close();
    } catch (Exception e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "Insert Error: " + e.getMessage());
    }



    }//GEN-LAST:event_btnInsertActionPerformed

    private void btnInsertActionListener(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertActionListener
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btnInsertActionListener

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
     
    try {
        Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/airport_db", "root", "");

        String sql = "DELETE FROM passengers WHERE passport_number = ?";

        PreparedStatement pstmt = conn.prepareStatement(sql);
        pstmt.setString(1, txtPassport.getText());

        int rows = pstmt.executeUpdate();
        if (rows > 0) {
            JOptionPane.showMessageDialog(this, "Passenger deleted successfully!");
            loadPassengerData();
        } else {
            JOptionPane.showMessageDialog(this, "No passenger found with that passport number.");
        }

        conn.close();
    } catch (Exception e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
    }


    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        
    try {
        Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/airport_db", "root", "");

        String sql = "UPDATE passengers SET name = ?, nationality = ?, gender = ?, date_of_birth = ?, flight_number = ?, seat_number = ?, check_in_status = ? WHERE passport_number = ?";

        PreparedStatement pstmt = conn.prepareStatement(sql);

        // Setting values from input fields
        pstmt.setString(1, txtName.getText());
        pstmt.setString(2, txtNationality.getText());
        pstmt.setString(3, comboGender.getSelectedItem().toString());

        // Parse date safely
        try {
            java.sql.Date dob = java.sql.Date.valueOf(txtDOB.getText()); // Format: yyyy-MM-dd
            pstmt.setDate(4, dob);
        } catch (IllegalArgumentException ex) {
            JOptionPane.showMessageDialog(this, "Invalid date format. Use yyyy-MM-dd.");
            conn.close();
            return;
        }

        pstmt.setString(5, txtFlight.getText());
        pstmt.setString(6, txtSeat.getText());
        pstmt.setBoolean(7, chkCheckIn.isSelected());

        pstmt.setString(8, txtPassport.getText()); // WHERE clause

        // Execute update
        int rows = pstmt.executeUpdate();
        if (rows > 0) {
            JOptionPane.showMessageDialog(this, "Passenger updated successfully!");
            loadPassengerData();
}
        else{
            JOptionPane.showMessageDialog(this, "No Passenger found with this passport number");
            
}

        conn.close();
    } catch (Exception e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
    }

    }//GEN-LAST:event_btnUpdateActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        new loginpage().setVisible(true);
    }//GEN-LAST:event_jButton1MouseClicked

    private void tablePassengersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablePassengersMouseClicked
        // TODO add your handling code here:
        int selectedRow = tablePassengers.getSelectedRow();
        if (selectedRow >= 0) {
            txtName.setText(tablePassengers.getValueAt(selectedRow, 0).toString());
            txtPassport.setText(tablePassengers.getValueAt(selectedRow, 1).toString());
            txtNationality.setText(tablePassengers.getValueAt(selectedRow, 2).toString());
            comboGender.setSelectedItem(tablePassengers.getValueAt(selectedRow, 3).toString());
            txtDOB.setText(tablePassengers.getValueAt(selectedRow, 4).toString());
            txtFlight.setText(tablePassengers.getValueAt(selectedRow, 5).toString());
            txtSeat.setText(tablePassengers.getValueAt(selectedRow, 6).toString());
           Object checkInValue = tablePassengers.getValueAt(selectedRow, 7);
if (checkInValue instanceof Boolean) {
    chkCheckIn.setSelected((Boolean) checkInValue);
} else {
    String value = checkInValue.toString().toLowerCase();
    chkCheckIn.setSelected(value.equals("true") || value.equals("yes") || value.equals("1"));
}
 
            txtPassport.setText(tablePassengers.getValueAt(selectedRow, 1).toString());
            txtPassport.setEditable(false); // Optional, to prevent changing the key
        }
    }//GEN-LAST:event_tablePassengersMouseClicked

    private void NextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NextActionPerformed
        // TODO add your handling code here:
        new ThankYouPage(); // Open the Thank You page
    this.dispose(); 
    }//GEN-LAST:event_NextActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PassengerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PassengerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PassengerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PassengerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PassengerForm().setVisible(true);
            }
        });
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Next;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnInsert;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JCheckBox chkCheckIn;
    private javax.swing.JComboBox<String> comboGender;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCheckIn;
    private javax.swing.JLabel lblDOB;
    private javax.swing.JLabel lblGender;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblNationality;
    private javax.swing.JLabel lblPassport;
    private javax.swing.JLabel lblSeat;
    private javax.swing.JScrollPane scrollPane;
    private javax.swing.JTable tablePassengers;
    private javax.swing.JTextField txtDOB;
    private javax.swing.JTextField txtFlight;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtNationality;
    private javax.swing.JTextField txtPassport;
    private javax.swing.JTextField txtSeat;
    // End of variables declaration//GEN-END:variables

   
      

    }



